// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGWhwnIdOmBbp8cIg_1A8bDleiE6aSOt0',
    appId: '1:45413334600:web:b74e35bf276a891f39a27d',
    messagingSenderId: '45413334600',
    projectId: 'chattytalk-2bfa9',
    authDomain: 'chattytalk-2bfa9.firebaseapp.com',
    storageBucket: 'chattytalk-2bfa9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF9seIFk5JptuK6f68qXFWudJ_fVBn8gM',
    appId: '1:45413334600:android:c1ef9531b8051d9139a27d',
    messagingSenderId: '45413334600',
    projectId: 'chattytalk-2bfa9',
    storageBucket: 'chattytalk-2bfa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6mLezH0oaBG6OfKs7NV_26uUOUPQzOQw',
    appId: '1:45413334600:ios:f51064c51863390c39a27d',
    messagingSenderId: '45413334600',
    projectId: 'chattytalk-2bfa9',
    storageBucket: 'chattytalk-2bfa9.appspot.com',
    iosClientId: '45413334600-jjut1e031gaba4iuaadt18jespbf6qtv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattytalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6mLezH0oaBG6OfKs7NV_26uUOUPQzOQw',
    appId: '1:45413334600:ios:f51064c51863390c39a27d',
    messagingSenderId: '45413334600',
    projectId: 'chattytalk-2bfa9',
    storageBucket: 'chattytalk-2bfa9.appspot.com',
    iosClientId: '45413334600-jjut1e031gaba4iuaadt18jespbf6qtv.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattytalk',
  );
}
